// map country names returned from expo-location reversegeocodeasync to
// gov.uk foreign-travel-advice slugs (mirrors usAdvisoryCountryMap.js).
//
// Fixes the bug where safetyPresenter.jsx used to derive the slug as
// `country.toLowerCase().replace(/\s+/g, "-")` — that breaks for any
// country whose real gov.uk slug isn't just its name lowercased with
// hyphens (accents, apostrophes, "St"/"Saint", old/alternate names, etc),
// e.g. "Côte d'Ivoire" -> "cote-d-ivoire", not "côte-d'ivoire".
//
// Source: https://www.gov.uk/api/content/foreign-travel-advice (the
// `links.children[].details.country.{name,slug}` list), plus a handful of
// manual aliases for names expo-location returns that gov.uk itself
// doesn't use (old country names, "DR Congo", etc). No entry exists for
// "United Kingdom"/"United States" travel advice pages since gov.uk
// doesn't publish travel advice about the UK itself or (for historical
// naming reasons) lists the US page under the "usa" slug — both handled
// as aliases below.
const countryToUKSlug = {
  "Afghanistan": "afghanistan",
  "Albania": "albania",
  "Algeria": "algeria",
  "Andorra": "andorra",
  "Angola": "angola",
  "Anguilla": "anguilla",
  "Antarctica": "antarctica-british-antarctic-territory",
  "Antarctica/British Antarctic Territory": "antarctica-british-antarctic-territory",
  "Antigua and Barbuda": "antigua-and-barbuda",
  "Argentina": "argentina",
  "Armenia": "armenia",
  "Aruba": "aruba",
  "Australia": "australia",
  "Austria": "austria",
  "Azerbaijan": "azerbaijan",
  "Bahamas": "bahamas",
  "Bahrain": "bahrain",
  "Bangladesh": "bangladesh",
  "Barbados": "barbados",
  "Belarus": "belarus",
  "Belgium": "belgium",
  "Belize": "belize",
  "Benin": "benin",
  "Bermuda": "bermuda",
  "Bhutan": "bhutan",
  "Bolivia": "bolivia",
  "Bonaire/St Eustatius/Saba": "bonaire-st-eustatius-saba",
  "Bosnia": "bosnia-and-herzegovina",
  "Bosnia and Herzegovina": "bosnia-and-herzegovina",
  "Botswana": "botswana",
  "Brazil": "brazil",
  "British Indian Ocean Territory": "british-indian-ocean-territory",
  "British Virgin Islands": "british-virgin-islands",
  "Brunei": "brunei",
  "Bulgaria": "bulgaria",
  "Burkina Faso": "burkina-faso",
  "Burma": "myanmar",
  "Burundi": "burundi",
  "Cabo Verde": "cape-verde",
  "Cambodia": "cambodia",
  "Cameroon": "cameroon",
  "Canada": "canada",
  "Cape Verde": "cape-verde",
  "Cayman Islands": "cayman-islands",
  "Central African Republic": "central-african-republic",
  "Chad": "chad",
  "Chile": "chile",
  "China": "china",
  "Colombia": "colombia",
  "Comoros": "comoros",
  "Congo": "congo",
  "Cook Islands, Tokelau and Niue": "cook-islands-tokelau-and-niue",
  "Costa Rica": "costa-rica",
  "Cote d'Ivoire": "cote-d-ivoire",
  "Côte d'Ivoire": "cote-d-ivoire",
  "Croatia": "croatia",
  "Cuba": "cuba",
  "Curaçao": "curacao",
  "Curacao": "curacao",
  "Cyprus": "cyprus",
  "Czechia": "czechia",
  "Czech Republic": "czechia",
  "Democratic Republic of the Congo": "democratic-republic-of-the-congo",
  "Denmark": "denmark",
  "Djibouti": "djibouti",
  "Dominica": "dominica",
  "Dominican Republic": "dominican-republic",
  "DR Congo": "democratic-republic-of-the-congo",
  "Ecuador": "ecuador",
  "Egypt": "egypt",
  "El Salvador": "el-salvador",
  "Equatorial Guinea": "equatorial-guinea",
  "Eritrea": "eritrea",
  "Estonia": "estonia",
  "Eswatini": "eswatini",
  "Swaziland": "eswatini",
  "Ethiopia": "ethiopia",
  "Falkland Islands": "falkland-islands",
  "Federated States of Micronesia": "federated-states-of-micronesia",
  "Fiji": "fiji",
  "Finland": "finland",
  "France": "france",
  "French Guiana": "french-guiana",
  "French Polynesia": "french-polynesia",
  "Gabon": "gabon",
  "Gambia": "the-gambia",
  "The Gambia": "the-gambia",
  "Georgia": "georgia",
  "Germany": "germany",
  "Ghana": "ghana",
  "Gibraltar": "gibraltar",
  "Greece": "greece",
  "Grenada": "grenada",
  "Guadeloupe": "guadeloupe",
  "Guatemala": "guatemala",
  "Guinea": "guinea",
  "Guinea-Bissau": "guinea-bissau",
  "Guyana": "guyana",
  "Haiti": "haiti",
  "Honduras": "honduras",
  "Hong Kong": "hong-kong",
  "Hungary": "hungary",
  "Iceland": "iceland",
  "India": "india",
  "Indonesia": "indonesia",
  "Iran": "iran",
  "Iraq": "iraq",
  "Ireland": "ireland",
  "Israel": "israel",
  "Italy": "italy",
  "Ivory Coast": "cote-d-ivoire",
  "Jamaica": "jamaica",
  "Japan": "japan",
  "Jordan": "jordan",
  "Kazakhstan": "kazakhstan",
  "Kenya": "kenya",
  "Kiribati": "kiribati",
  "Korea, Republic of": "south-korea",
  "Kosovo": "kosovo",
  "Kuwait": "kuwait",
  "Kyrgyzstan": "kyrgyzstan",
  "The Kyrgyz Republic": "kyrgyzstan",
  "Laos": "laos",
  "Latvia": "latvia",
  "Lebanon": "lebanon",
  "Lesotho": "lesotho",
  "Liberia": "liberia",
  "Libya": "libya",
  "Liechtenstein": "liechtenstein",
  "Lithuania": "lithuania",
  "Luxembourg": "luxembourg",
  "Macao": "macao",
  "Macau": "macao",
  "Macedonia": "north-macedonia",
  "Madagascar": "madagascar",
  "Malawi": "malawi",
  "Malaysia": "malaysia",
  "Maldives": "maldives",
  "Mali": "mali",
  "Malta": "malta",
  "Marshall Islands": "marshall-islands",
  "Martinique": "martinique",
  "Mauritania": "mauritania",
  "Mauritius": "mauritius",
  "Mayotte": "mayotte",
  "Mexico": "mexico",
  "Micronesia": "federated-states-of-micronesia",
  "Moldova": "moldova",
  "Monaco": "monaco",
  "Mongolia": "mongolia",
  "Montenegro": "montenegro",
  "Montserrat": "montserrat",
  "Morocco": "morocco",
  "Mozambique": "mozambique",
  "Myanmar": "myanmar",
  "Myanmar (Burma)": "myanmar",
  "Namibia": "namibia",
  "Nauru": "nauru",
  "Nepal": "nepal",
  "Netherlands": "netherlands",
  "New Caledonia": "new-caledonia",
  "New Zealand": "new-zealand",
  "Nicaragua": "nicaragua",
  "Niger": "niger",
  "Nigeria": "nigeria",
  "North Korea": "north-korea",
  "North Macedonia": "north-macedonia",
  "Norway": "norway",
  "Oman": "oman",
  "Pakistan": "pakistan",
  "Palau": "palau",
  "Palestine": "palestine",
  "Panama": "panama",
  "Papua New Guinea": "papua-new-guinea",
  "Paraguay": "paraguay",
  "Peru": "peru",
  "Philippines": "philippines",
  "Pitcairn Island": "pitcairn-island",
  "Poland": "poland",
  "Portugal": "portugal",
  "Qatar": "qatar",
  "Republic of the Congo": "congo",
  "Réunion": "reunion",
  "Reunion": "reunion",
  "Romania": "romania",
  "Russia": "russia",
  "Rwanda": "rwanda",
  "Saint Kitts and Nevis": "st-kitts-and-nevis",
  "Saint Lucia": "st-lucia",
  "Saint Vincent and the Grenadines": "st-vincent-and-the-grenadines",
  "Samoa": "samoa",
  "San Marino": "san-marino",
  "São Tomé and Principe": "sao-tome-and-principe",
  "Sao Tome and Principe": "sao-tome-and-principe",
  "Saudi Arabia": "saudi-arabia",
  "Senegal": "senegal",
  "Serbia": "serbia",
  "Seychelles": "seychelles",
  "Sierra Leone": "sierra-leone",
  "Singapore": "singapore",
  "Slovakia": "slovakia",
  "Slovenia": "slovenia",
  "Solomon Islands": "solomon-islands",
  "Somalia": "somalia",
  "South Africa": "south-africa",
  "South Georgia and the South Sandwich Islands": "south-georgia-and-south-sandwich-islands",
  "South Korea": "south-korea",
  "South Sudan": "south-sudan",
  "Spain": "spain",
  "Sri Lanka": "sri-lanka",
  "St Helena, Ascension and Tristan da Cunha": "st-helena-ascension-and-tristan-da-cunha",
  "St Kitts and Nevis": "st-kitts-and-nevis",
  "St Lucia": "st-lucia",
  "St Maarten": "st-maarten",
  "Sint Maarten": "st-maarten",
  "St Martin and St Barthélemy": "st-martin-and-st-barthelemy",
  "St Pierre & Miquelon": "st-pierre-and-miquelon",
  "St Vincent and the Grenadines": "st-vincent-and-the-grenadines",
  "Sudan": "sudan",
  "Suriname": "suriname",
  "Sweden": "sweden",
  "Switzerland": "switzerland",
  "Syria": "syria",
  "Taiwan": "taiwan",
  "Tajikistan": "tajikistan",
  "Tanzania": "tanzania",
  "Thailand": "thailand",
  "The Bahamas": "bahamas",
  "Timor-Leste": "timor-leste",
  "East Timor": "timor-leste",
  "Togo": "togo",
  "Tonga": "tonga",
  "Trinidad and Tobago": "trinidad-and-tobago",
  "Tunisia": "tunisia",
  "Turkey": "turkey",
  "Turkmenistan": "turkmenistan",
  "Turks and Caicos Islands": "turks-and-caicos-islands",
  "Tuvalu": "tuvalu",
  "Uganda": "uganda",
  "Ukraine": "ukraine",
  "United Arab Emirates": "united-arab-emirates",
  "United States": "usa",
  "Uruguay": "uruguay",
  "USA": "usa",
  "Uzbekistan": "uzbekistan",
  "Vanuatu": "vanuatu",
  "Venezuela": "venezuela",
  "Viet Nam": "vietnam",
  "Vietnam": "vietnam",
  "Wallis and Futuna": "wallis-and-futuna",
  "Western Sahara": "western-sahara",
  "Yemen": "yemen",
  "Zambia": "zambia",
  "Zimbabwe": "zimbabwe",
};

export function getUKAdvisorySlug(countryName) {
  if (!countryName) return null;
  return countryToUKSlug[countryName] || null;
}
